### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by DanteAlucard98** [hamzasidd3634/camera_filter#1]
help please, i'm interested for your plugin, it's awesome how change the color in the screen but i can´t take a picture like your screenshots and video. Can you help me please?

**Comment by hamzasidd3634** [comment]
please share your code so i can understand your problem

**Comment by DanteAlucard98** [comment]
ok i use your example from git hub 
![image](https://user-images.githubusercontent.com/34227437/168491342-ab7b5169-08cb-4390-81f5-3f5534130280.png)
but when i take a photo i have this
![image](https://user-images.githubusercontent.com/34227437/168491396-3ba2a014-f389-4e44-aa5f-eb2cc707954e.png)
and when i try to take other photo i have a new error
![image](https://user-images.githubusercontent.com/34227437/168491431-9a24efed-e17d-4713-abe7-40cc32e60ac2.png)

**Comment by hamzasidd3634** [comment]
i will resolve this issue ASAP

**Comment by hamzasidd3634** [comment]
problem is solved in latest version, I'm closing this issue if you face any problem again you can reopen this issue or file an another issue.. Thanks for using this package..
